alias lsl="ls -lah"
alias consumer="cd ~/dev/consumer"
alias reload="exec $SHELL -l"

me="~/dotfiles/aliases.sh"

alias editaliases="vim ${me}"
alias editprofile="vim ~/.profile"
alias editvimrc="vim ~/.vimrc"

alias showvimrc="cat ~/.vimrc"
alias showaliases="cat ${me}"
alias showprofile="cat ~/.profile"

alias gits="git status"
alias gitco="git checkout"
alias gitcob="git checkout -b"
alias gpo="git push origin"
alias gp="git push -v"
alias gpom="git push origin master"
alias glol="git log --oneline"
alias ga="git add --all"
alias gcm="git commit -m"
alias gd="git diff"
alias grhh="git reset --hard HEAD"

alias b="bundle"
alias be="bundle exec"
alias bi="bundle install"
alias bu="bundle update"
alias bers="bundle exec rails server"
alias bersp="bundle exec rspec"
alias berp="bundle exec rackup"
alias berc="bundle exec rails console"
alias brakt="bundle exec rake -T"
alias brake="bundle exec rake"
alias beru="bundle exec rackup"
alias bpry="bundle exec pry"
alias blasterpull="git checkout master && git pull && bundle install"
alias masterpull="git checkout master && git pull"
alias cov="open coverage/index.html"

alias gtest="./gradlew test"
alias gbuild="./gradlew build"
alias gdeps="./gradlew dependencies"
alias jetrun="./gradlew jettyRun --info"
